--liquibase formatted sql

--changeset serhiiboiko:lessons

INSERT INTO lesson(clazz_id, subject_id, date, file, hometask, lesson_number, mark_type) VALUES
((SELECT id FROM clazz WHERE name = '5-A'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-22', null, 'ознайомитися з Microsoft Word', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '5-A'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-22', null, 'ex. 4, 5 page 5', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '5-A'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-22', LOAD_FILE('ukrainska.doc'), 'прочитати параграф 1', 3, 'Practic'),
((SELECT id FROM clazz where name = '8-A'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-22', LOAD_FILE('data.png'), 'впр. 54 ст. 123', 1, 'Practic'),
((SELECT id FROM clazz where name = '8-A'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-22', LOAD_FILE('file.txt'), 'впр. 2 ст. 10', 2, 'Labaratorna'),
((SELECT id FROM clazz where name = '8-A'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-22', null, 'Пісні Марусі Чурай "Засвіт встали козаченьки" (напам’ять)', 3, 'Practic'),
((SELECT id FROM clazz where name = '8-A'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-22', LOAD_FILE('homework.txt'), 'ex. 3 page 12', 4, 'Control'),
((SELECT id FROM clazz where name = '8-A'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-22', LOAD_FILE('task.doc'), 'впр. 54, 55, 57 ст. 123', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-03', null, 'Домашнє завдання #56, #83', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-03', null, 'Домашнє завдання #45, #56', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-03', null, 'Домашнє завдання #10, #95', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-03', null, 'Домашнє завдання #41, #33', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-03', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-04', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-04', null, 'Домашнє завдання #2, #50', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-04', null, 'Домашнє завдання #98, #69', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-04', null, 'Домашнє завдання #98, #12', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-04', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-04', null, 'Домашнє завдання #37, #36', 6, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-05', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-05', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-05', null, 'Домашнє завдання #61, #32', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-05', null, 'Домашнє завдання #6, #74', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-05', null, 'Домашнє завдання #33, #3', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-06', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-06', null, 'Домашнє завдання #14, #81', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-06', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-06', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-06', null, 'Домашнє завдання #66, #56', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-07', null, 'Домашнє завдання #23, #45', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-07', null, 'Домашнє завдання #94, #4', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-07', null, 'Домашнє завдання #55, #91', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-07', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-10', null, 'Домашнє завдання #17, #92', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-10', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-10', null, 'Домашнє завдання #78, #17', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-10', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-10', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-11', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-11', null, 'Домашнє завдання #46, #28', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-11', null, 'Домашнє завдання #43, #54', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-11', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-11', null, 'Домашнє завдання #77, #21', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-11', null, 'Домашнє завдання #14, #9', 6, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-12', null, 'Домашнє завдання #20, #0', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-12', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-12', null, 'Домашнє завдання #99, #28', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-12', null, 'Домашнє завдання #60, #11', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-12', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-13', null, 'Домашнє завдання #21, #78', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-13', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-13', null, 'Домашнє завдання #83, #2', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-13', null, 'Домашнє завдання #67, #36', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-13', null, 'Домашнє завдання #52, #63', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-14', null, 'Домашнє завдання #20, #88', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-14', null, 'Домашнє завдання #37, #52', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-14', null, 'Домашнє завдання #94, #31', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-14', null, 'Домашнє завдання #23, #46', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-17', null, 'Домашнє завдання #70, #64', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-17', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-17', null, 'Домашнє завдання #47, #76', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-17', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-17', null, 'Домашнє завдання #66, #10', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-18', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-18', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-18', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-18', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-18', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-18', null, '', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-19', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-19', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-19', null, 'Домашнє завдання #32, #4', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-19', null, 'Домашнє завдання #86, #30', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-19', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-20', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-20', null, 'Домашнє завдання #12, #77', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-20', null, 'Домашнє завдання #87, #24', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-20', null, 'Домашнє завдання #84, #12', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-20', null, 'Домашнє завдання #52, #65', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-21', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-21', null, 'Домашнє завдання #55, #85', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-21', null, 'Домашнє завдання #78, #6', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-21', null, 'Домашнє завдання #70, #13', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-24', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-24', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-24', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-24', null, 'Домашнє завдання #77, #16', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-24', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-25', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-25', null, 'Домашнє завдання #89, #8', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-25', null, 'Домашнє завдання #21, #2', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-25', null, 'Домашнє завдання #70, #81', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-25', null, 'Домашнє завдання #64, #27', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-25', null, 'Домашнє завдання #17, #45', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-26', null, 'Домашнє завдання #45, #50', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-26', null, 'Домашнє завдання #98, #39', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-26', null, 'Домашнє завдання #58, #75', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-26', null, 'Домашнє завдання #13, #81', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-26', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-27', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-27', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-27', null, 'Домашнє завдання #50, #22', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-27', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-27', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-28', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-28', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-28', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-28', null, 'Домашнє завдання #26, #10', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-01', null, 'Домашнє завдання #32, #23', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-01', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-01', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-01', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-01', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-02', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-02', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-02', null, 'Домашнє завдання #66, #26', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-02', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-02', null, 'Домашнє завдання #49, #56', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-02', null, '', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-03', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-03', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-03', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-03', null, 'Домашнє завдання #85, #9', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-03', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-04', null, 'Домашнє завдання #32, #91', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-04', null, 'Домашнє завдання #38, #80', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-04', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-04', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-04', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-05', null, 'Домашнє завдання #24, #20', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-05', null, 'Домашнє завдання #84, #75', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-05', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-05', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-08', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-08', null, 'Домашнє завдання #57, #2', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-08', null, 'Домашнє завдання #14, #13', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-08', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-08', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-09', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-09', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-09', null, 'Домашнє завдання #61, #65', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-09', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-09', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-09', null, 'Домашнє завдання #11, #89', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-10', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-10', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-10', null, 'Домашнє завдання #87, #53', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-10', null, 'Домашнє завдання #69, #11', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-10', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-11', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-11', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-11', null, 'Домашнє завдання #1, #37', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-11', null, 'Домашнє завдання #13, #3', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-11', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-12', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-12', null, 'Домашнє завдання #23, #53', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-12', null, 'Домашнє завдання #40, #22', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-12', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-15', null, 'Домашнє завдання #54, #71', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-15', null, 'Домашнє завдання #20, #7', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-15', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-15', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-15', null, 'Домашнє завдання #51, #13', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-16', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-16', null, 'Домашнє завдання #9, #50', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-16', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-16', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-16', null, 'Домашнє завдання #26, #91', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-16', null, 'Домашнє завдання #29, #14', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-17', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-17', null, 'Домашнє завдання #74, #16', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-17', null, 'Домашнє завдання #18, #42', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-17', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-17', null, 'Домашнє завдання #54, #92', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-18', null, 'Домашнє завдання #37, #10', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-18', null, 'Домашнє завдання #26, #93', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-18', null, 'Домашнє завдання #17, #30', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-18', null, 'Домашнє завдання #37, #72', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-18', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-19', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-19', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-19', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-19', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-22', LOAD_FILE('inf.doc'), 'ex. 8-16 page 30', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-22', null, '"Віють вітри, віють буйні" (читати)', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-22', null, 'вивчити параграф 5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-22', LOAD_FILE('homework.txt'), 'вивчити параграф 2', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-22', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-23', null, 'Домашнє завдання #26, #13', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-23', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-23', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-23', null, 'Домашнє завдання #60, #79', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-23', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-23', null, 'Домашнє завдання #5, #13', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-24', null, 'Домашнє завдання #35, #19', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-24', null, 'Домашнє завдання #13, #15', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-24', null, 'Домашнє завдання #46, #15', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-24', null, 'Домашнє завдання #93, #61', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-24', null, 'Домашнє завдання #2, #41', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-25', null, 'Домашнє завдання #91, #87', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-25', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-25', null, 'Домашнє завдання #39, #18', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-25', null, 'Домашнє завдання #18, #14', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-25', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-26', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-26', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-26', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-26', null, 'Домашнє завдання #20, #22', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-29', null, 'Домашнє завдання #42, #84', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-29', null, 'Домашнє завдання #62, #61', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-29', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-29', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-29', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-30', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-30', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-30', null, 'Домашнє завдання #47, #5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-30', null, 'Домашнє завдання #28, #43', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-30', null, 'Домашнє завдання #68, #46', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-30', null, '', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-31', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-31', null, 'Домашнє завдання #32, #24', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-31', null, 'Домашнє завдання #78, #10', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-31', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-31', null, 'Домашнє завдання #13, #83', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Математика'), '2018-11-01', null, 'Домашнє завдання #71, #56', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-11-01', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-11-01', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-11-01', null, 'Домашнє завдання #30, #48', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Географія'), '2018-11-01', null, 'Домашнє завдання #26, #28', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-11-02', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-11-02', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-11-02', null, 'Домашнє завдання #12, #5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-A' ), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-11-02', null, 'Домашнє завдання #30, #9', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-03', null, 'Домашнє завдання #56, #83', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-03', null, 'Домашнє завдання #45, #56', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-03', null, 'Домашнє завдання #10, #95', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-03', null, 'Домашнє завдання #41, #33', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-03', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-04', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-04', null, 'Домашнє завдання #2, #50', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-04', null, 'Домашнє завдання #98, #69', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-04', null, 'Домашнє завдання #98, #12', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-04', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-04', null, 'Домашнє завдання #37, #36', 6, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-05', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-05', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-05', null, 'Домашнє завдання #61, #32', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-06', null, 'Домашнє завдання #6, #74', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-06', null, 'Домашнє завдання #33, #3', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-06', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-07', null, 'Домашнє завдання #14, #81', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-07', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-07', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-07', null, 'Домашнє завдання #66, #56', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-07', null, 'Домашнє завдання #23, #45', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-10', null, 'Домашнє завдання #17, #92', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-10', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-10', null, 'Домашнє завдання #78, #17', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-10', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-10', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-11', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-11', null, 'Домашнє завдання #46, #28', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-11', null, 'Домашнє завдання #43, #54', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-11', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-11', null, 'Домашнє завдання #77, #21', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-11', null, 'Домашнє завдання #14, #9', 6, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-12', null, 'Домашнє завдання #20, #0', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-12', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-12', null, 'Домашнє завдання #99, #28', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-13', null, 'Домашнє завдання #60, #11', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-13', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-13', null, 'Домашнє завдання #21, #78', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-14', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-14', null, 'Домашнє завдання #83, #2', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-14', null, 'Домашнє завдання #67, #36', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-14', null, 'Домашнє завдання #52, #63', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-14', null, 'Домашнє завдання #20, #88', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-17', null, 'Домашнє завдання #70, #64', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-17', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-17', null, 'Домашнє завдання #47, #76', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-17', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-17', null, 'Домашнє завдання #66, #10', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-18', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-18', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-18', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-18', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-18', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-18', null, '', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-19', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-19', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-19', null, 'Домашнє завдання #32, #4', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-20', null, 'Домашнє завдання #86, #30', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-20', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-20', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-21', null, 'Домашнє завдання #12, #77', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-21', null, 'Домашнє завдання #87, #24', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-21', null, 'Домашнє завдання #84, #12', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-21', null, 'Домашнє завдання #52, #65', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-21', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-24', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-24', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-24', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-24', null, 'Домашнє завдання #77, #16', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-24', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-09-25', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-25', null, 'Домашнє завдання #89, #8', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-25', null, 'Домашнє завдання #21, #2', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-25', null, 'Домашнє завдання #70, #81', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-25', null, 'Домашнє завдання #64, #27', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-25', null, 'Домашнє завдання #17, #45', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-26', null, 'Домашнє завдання #45, #50', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-26', null, 'Домашнє завдання #98, #39', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-26', null, 'Домашнє завдання #58, #75', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-27', null, 'Домашнє завдання #13, #81', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-27', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-27', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-28', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-28', null, 'Домашнє завдання #50, #22', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-28', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-28', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-28', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-01', null, 'Домашнє завдання #32, #23', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-01', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-01', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-01', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-01', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-02', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-02', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-02', null, 'Домашнє завдання #66, #26', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-02', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-02', null, 'Домашнє завдання #49, #56', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-02', null, '', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-03', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-03', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-03', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-04', null, 'Домашнє завдання #85, #9', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-04', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-04', null, 'Домашнє завдання #32, #91', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-05', null, 'Домашнє завдання #38, #80', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-05', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-05', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-05', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-05', null, 'Домашнє завдання #24, #20', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-08', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-08', null, 'Домашнє завдання #57, #2', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-08', null, 'Домашнє завдання #14, #13', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-08', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-08', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-09', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-09', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-09', null, 'Домашнє завдання #61, #65', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-09', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-09', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-09', null, 'Домашнє завдання #11, #89', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-10', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-10', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-10', null, 'Домашнє завдання #87, #53', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-11', null, 'Домашнє завдання #69, #11', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-11', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-11', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-12', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-12', null, 'Домашнє завдання #1, #37', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-12', null, 'Домашнє завдання #13, #3', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-12', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-12', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-15', null, 'Домашнє завдання #54, #71', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-15', null, 'Домашнє завдання #20, #7', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-15', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-15', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-15', null, 'Домашнє завдання #51, #13', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-16', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-16', null, 'Домашнє завдання #9, #50', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-16', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-16', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-16', null, 'Домашнє завдання #26, #91', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-16', null, 'Домашнє завдання #29, #14', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-17', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-17', null, 'Домашнє завдання #74, #16', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-17', null, 'Домашнє завдання #18, #42', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-18', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-18', null, 'Домашнє завдання #54, #92', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-18', null, 'Домашнє завдання #37, #10', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-19', null, 'Домашнє завдання #26, #93', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-19', null, 'Домашнє завдання #17, #30', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-19', null, 'Домашнє завдання #37, #72', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-19', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-19', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-22', LOAD_FILE('teorema.doc'), '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-22', null, 'прочитати параграф 3', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-22', LOAD_FILE('help.doc'), 'ознайомитися з Excel', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-22', LOAD_FILE('homework.txt'), 'вивчити теорему Піфагора', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-22', null, 'ex. 29, 30 page 35', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-23', null, 'Домашнє завдання #26, #13', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-23', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-23', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-23', null, 'Домашнє завдання #60, #79', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-23', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-23', null, 'Домашнє завдання #5, #13', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-24', null, 'Домашнє завдання #35, #19', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-24', null, 'Домашнє завдання #13, #15', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-24', null, 'Домашнє завдання #46, #15', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-25', null, 'Домашнє завдання #93, #61', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-25', null, 'Домашнє завдання #2, #41', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-25', null, 'Домашнє завдання #91, #87', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-26', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-26', null, 'Домашнє завдання #39, #18', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-26', null, 'Домашнє завдання #18, #14', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-26', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-26', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-29', null, 'Домашнє завдання #42, #84', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-29', null, 'Домашнє завдання #62, #61', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-29', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-29', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-29', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська література'), '2018-10-30', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-30', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-30', null, 'Домашнє завдання #47, #5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-30', null, 'Домашнє завдання #28, #43', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-30', null, 'Домашнє завдання #68, #46', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-30', null, '', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-31', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-31', null, 'Домашнє завдання #32, #24', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-31', null, 'Домашнє завдання #78, #10', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-11-01', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-11-01', null, 'Домашнє завдання #13, #83', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-11-01', null, 'Домашнє завдання #71, #56', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-11-02', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-11-02', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-11-02', null, 'Домашнє завдання #30, #48', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-11-02', null, 'Домашнє завдання #26, #28', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '7-Б'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-11-02', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-03', null, 'Домашнє завдання #56, #83', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-03', null, 'Домашнє завдання #45, #56', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-03', null, 'Домашнє завдання #10, #95', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-03', null, 'Домашнє завдання #41, #33', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-03', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-04', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-04', null, 'Домашнє завдання #2, #50', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-04', null, 'Домашнє завдання #98, #69', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-04', null, 'Домашнє завдання #98, #12', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-04', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-05', null, 'Домашнє завдання #37, #36', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-05', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-05', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-05', null, 'Домашнє завдання #61, #32', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-05', null, 'Домашнє завдання #6, #74', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-06', null, 'Домашнє завдання #33, #3', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-06', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-06', null, 'Домашнє завдання #14, #81', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-06', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-06', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-06', null, 'Домашнє завдання #66, #56', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-07', null, 'Домашнє завдання #23, #45', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-07', null, 'Домашнє завдання #94, #4', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-07', null, 'Домашнє завдання #55, #91', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-07', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-10', null, 'Домашнє завдання #17, #92', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-10', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-10', null, 'Домашнє завдання #78, #17', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-10', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-10', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-11', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-11', null, 'Домашнє завдання #46, #28', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-11', null, 'Домашнє завдання #43, #54', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-11', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-11', null, 'Домашнє завдання #77, #21', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-12', null, 'Домашнє завдання #14, #9', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-12', null, 'Домашнє завдання #20, #0', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-12', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-12', null, 'Домашнє завдання #99, #28', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-12', null, 'Домашнє завдання #60, #11', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-13', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-13', null, 'Домашнє завдання #21, #78', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-13', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-13', null, 'Домашнє завдання #83, #2', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-13', null, 'Домашнє завдання #67, #36', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-13', null, 'Домашнє завдання #52, #63', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-14', null, 'Домашнє завдання #20, #88', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-14', null, 'Домашнє завдання #37, #52', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-14', null, 'Домашнє завдання #94, #31', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-14', null, 'Домашнє завдання #23, #46', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-17', null, 'Домашнє завдання #70, #64', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-17', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-17', null, 'Домашнє завдання #47, #76', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-17', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-17', null, 'Домашнє завдання #66, #10', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-18', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-18', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-18', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-18', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-18', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-19', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-19', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-19', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-19', null, 'Домашнє завдання #32, #4', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-19', null, 'Домашнє завдання #86, #30', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-20', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-20', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-20', null, 'Домашнє завдання #12, #77', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-20', null, 'Домашнє завдання #87, #24', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-20', null, 'Домашнє завдання #84, #12', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-20', null, 'Домашнє завдання #52, #65', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-21', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-21', null, 'Домашнє завдання #55, #85', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-21', null, 'Домашнє завдання #78, #6', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-21', null, 'Домашнє завдання #70, #13', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-24', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-24', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-24', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-24', null, 'Домашнє завдання #77, #16', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-24', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-25', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-25', null, 'Домашнє завдання #89, #8', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-09-25', null, 'Домашнє завдання #21, #2', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-25', null, 'Домашнє завдання #70, #81', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-25', null, 'Домашнє завдання #64, #27', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-09-26', null, 'Домашнє завдання #17, #45', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-26', null, 'Домашнє завдання #45, #50', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-26', null, 'Домашнє завдання #98, #39', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-26', null, 'Домашнє завдання #58, #75', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-09-26', null, 'Домашнє завдання #13, #81', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-09-27', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-09-27', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-27', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-09-27', null, 'Домашнє завдання #50, #22', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-27', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-27', null, '', 6, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-28', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-09-28', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-09-28', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-09-28', null, 'Домашнє завдання #26, #10', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-01', null, 'Домашнє завдання #32, #23', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-01', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-01', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-01', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-01', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-02', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-02', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-02', null, 'Домашнє завдання #66, #26', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-02', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-02', null, 'Домашнє завдання #49, #56', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-03', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-03', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-03', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-03', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-03', null, 'Домашнє завдання #85, #9', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-04', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-04', null, 'Домашнє завдання #32, #91', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-04', null, 'Домашнє завдання #38, #80', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-04', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-04', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-04', null, '', 6, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-05', null, 'Домашнє завдання #24, #20', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-05', null, 'Домашнє завдання #84, #75', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-05', null, '', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-05', null, '', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-08', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-08', null, 'Домашнє завдання #57, #2', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-08', null, 'Домашнє завдання #14, #13', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-08', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-08', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-09', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-09', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-09', null, 'Домашнє завдання #61, #65', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-09', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-09', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-10', null, 'Домашнє завдання #11, #89', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-10', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-10', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-10', null, 'Домашнє завдання #87, #53', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-10', null, 'Домашнє завдання #69, #11', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-11', null, '', 1, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-11', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-11', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-11', null, 'Домашнє завдання #1, #37', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-11', null, 'Домашнє завдання #13, #3', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-11', null, '', 6, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-12', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-12', null, 'Домашнє завдання #23, #53', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-12', null, 'Домашнє завдання #40, #22', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-12', null, '', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-15', null, 'Домашнє завдання #54, #71', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-15', null, 'Домашнє завдання #20, #7', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-15', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-15', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-15', null, 'Домашнє завдання #51, #13', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-16', null, '', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-16', null, 'Домашнє завдання #9, #50', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-16', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-16', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-16', null, 'Домашнє завдання #26, #91', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-17', null, 'Домашнє завдання #29, #14', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-17', null, '', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-17', null, 'Домашнє завдання #74, #16', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-17', null, 'Домашнє завдання #18, #42', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-17', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-18', null, 'Домашнє завдання #54, #92', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-18', null, 'Домашнє завдання #37, #10', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-18', null, 'Домашнє завдання #26, #93', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-18', null, 'Домашнє завдання #17, #30', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-18', null, 'Домашнє завдання #37, #72', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-18', null, '', 6, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-19', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-19', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-19', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-19', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-22', null, 'підготуватися то контрольної роботи', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-22', LOAD_FILE('fiz.doc'), 'впр. 23, 24, 25, 28 ст. 41', 2, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-22', LOAD_FILE('ukrainska.doc'), 'впр. 23, 24, 25, 28 ст. 41', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-22', null, 'Домашнє завдання #8, #15', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-22', null, '', 5, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-23', null, 'Домашнє завдання #26, #13', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-23', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-23', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-23', null, 'Домашнє завдання #60, #79', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-23', null, '', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-24', null, 'Домашнє завдання #5, #13', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-24', null, 'Домашнє завдання #35, #19', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-24', null, 'Домашнє завдання #13, #15', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-24', null, 'Домашнє завдання #46, #15', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-24', null, 'Домашнє завдання #93, #61', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-25', null, 'Домашнє завдання #2, #41', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-25', null, 'Домашнє завдання #91, #87', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-25', null, '', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-25', null, 'Домашнє завдання #39, #18', 4, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-25', null, 'Домашнє завдання #18, #14', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-25', null, '', 6, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-26', null, '', 1, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-26', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-26', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-10-26', null, 'Домашнє завдання #20, #22', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-29', null, 'Домашнє завдання #42, #84', 1, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-10-29', null, 'Домашнє завдання #62, #61', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-29', null, '', 3, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-29', null, '', 4, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-10-29', null, '', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-30', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-30', null, '', 2, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Біологія'), '2018-10-30', null, 'Домашнє завдання #47, #5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-30', null, 'Домашнє завдання #28, #43', 4, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-10-30', null, 'Домашнє завдання #68, #46', 5, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Історія України'), '2018-10-31', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-31', null, '', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-10-31', null, 'Домашнє завдання #32, #24', 3, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-10-31', null, 'Домашнє завдання #78, #10', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Географія'), '2018-10-31', null, '', 5, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Математика'), '2018-11-01', null, 'Домашнє завдання #13, #83', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Фізика'), '2018-11-01', null, 'Домашнє завдання #71, #56', 2, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-11-01', null, '', 3, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Англійська мова'), '2018-11-01', null, '', 4, 'Control'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-11-01', null, 'Домашнє завдання #30, #48', 5, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-11-01', null, 'Домашнє завдання #26, #28', 6, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-11-02', null, '', 1, 'Labaratorna'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Українська мова'), '2018-11-02', null, '', 2, 'Module'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Хімія'), '2018-11-02', null, 'Домашнє завдання #12, #5', 3, 'Practic'),
((SELECT id FROM clazz WHERE name = '9'), (SELECT id FROM subject WHERE name = 'Інформатика'), '2018-11-02', null, 'Домашнє завдання #30, #9', 4, 'Module');

